### ISSUE TITLE
Consumer API => UserDomain Adapter

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/ProcessEngine.CompatibilityProxyAdapter#1]
Der Adapter soll einen HTTP Endpunkt bereitstellen, der dem der alten [Consumer API](https://github.com/process-engine/consumer_api_http) entspricht.

Die hier exposten Routen müssen deckungsgleich sein, damit der ConsumerApiClient diese benutzen kann.

Über den Controller soll dann ein `ProxyService` (Vorschläge für bessere Namen sind gerne willkommen), der diese Requests entgegennimmt und gegen die Services der [AtlasEngine-UserDomain](https://github.com/atlas-engine/UserDomain.Core/tree/develop/user_domain.services) ausführt.

Da der Proxy direkt in den Fullstack Server integriert werden soll, muss hier nicht der Umweg über den HTTP Client gemacht werden, sondern die Services können direkt angesteuert werden.

Die Ergebnisse, die von der UserDomain zurückgegeben werden, müssen dann in das ConsumerAPI Format transformiert und zurückgegben werden.

**Wichtig:**
Das ganze soll **ein einzelnes** NPM Paket werden: `@atlas-engine/process_engine.proxy.consumer_api` wäre mein Vorschlag als npm Paketname. 
Wenn später ein vergleichbarer Proxy für die Management API implementiert wird, könnte man diesen dann `@atlas-engine/process_engine.proxy.management_api` nennen.

Die Test für diesen Adapter sollen im Fullstack Server liegen und den alten Tests für die ConsumerAPI entsprechen. 
Dafür muss der [ConsumerApiClient](https://github.com/process-engine/consumer_api_client/tree/develop/typescript) genutzt werden.

**Comment by rrrene** [comment]
@ElRaptorus bitte den Issue-Text nochmal editieren und beschreiben, wie @moellenbeck es jetzt schlussendlich vorgegeben hat 👍

**Comment by ElRaptorus** [comment]
@rrrene done
