### ISSUE TITLE
Correlations seem to be ordered createdAt ASC by default

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/ProcessEngine.CompatibilityProxyAdapter#10]
Wenn ich offset=0 und limit=1 nutze, hätte ich erwartet, die neuste Correlation zu bekommen. Ich bekomme aber die älteste, was wahrscheinlich fast nie das ist, was ich mit folgendem Code erreichen will:

```typescript
this.managementApiClient.getAllCorrelations(this.identity, 0, 1)
```

Bitte einmal prüfen, wie das in der PE implementiert ist und im Zweifelsfall sowohl in PE als auch hier im PE-Adapter anpassen.

**Comment by ElRaptorus** [comment]
@rrrene Wie schauts aus, funktioniert das jetzt auch in der CLI?

**Comment by ElRaptorus** [comment]
@rrrene Bump

**Comment by rrrene** [comment]
Ah, übersehen. Thx! 👍

Wir können das schließen, weil die CLI sowieso selber sortiert, um mit älteren PEs noch kompatibel zu sein.
