### ISSUE TITLE
Deployment "fails" silently for some diagrams

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/ProcessEngine.CompatibilityProxyAdapter#5]
Das Deployen mancher Diagramme schlägt fehl (siehe unten). Nach kurzer Analyse bin ich darauf gekommen, dass das an der `definitionId` liegen wird (die ist in manchen der Prozesse identisch: `Definition_1`).

Die Gretchen-Frage ist nun: Wie gehen wir damit um, damit der ProcessEngine.CompatibilityProxyAdapter wie eine ProcessEngine funktioniert? Meiner Meinung nach muss da eine Weiche rein, dass bei `Definition_1` die `processModelId` anstelle der `definitionId` genommen wird.

Denn das ich 6 Prozesse erfolgreich deploye und dann "nur zwei ankommen" ist schwierig (dass `fixtures/Elements.bpmn` nicht deployt werden kann ist richtig und gewollt):

## Reproduktion

[Atlas CLI](https://github.com/atlas-engine/cli) installieren (`npm install -g @atlas-engine/cli`) und im geklonten Repo der Atlas CLI versuchen, die [Fixtures](https://github.com/atlas-engine/cli/tree/develop/fixtures) auf eine AtlasEngine zu laden:

```shell
$ atlas login http://0.0.0.0:8000 --root

Anonymous root login successful. No further steps required.

You are now logged in.


$ atlas lsp
┌─────────┐
│ (index) │
├─────────┤
└─────────┘


$ atlas deploy fixtures/*.bpmn
fixtures/Aktivierungs-E-Mails-Prozess.bpmn -> Process_1 [deployed]
fixtures/Elements.bpmn -> Elements [failed]
UnprocessableEntityError: The xml could not be parsed.
fixtures/Wartung.EMailsVerschicken.bpmn -> Wartung.EMailsVerschicken [deployed]
fixtures/Wartung.FehlerProvozieren.bpmn -> Wartung.FehlerProvozieren [deployed]
fixtures/Wartung.SekundenWarten.bpmn -> Wartung.SekundenWarten [deployed]
fixtures/Wartung.StringUmdrehen.bpmn -> Wartung.StringUmdrehen [deployed]
fixtures/wait-demo.bpmn -> wait_demo [deployed]

** (Atlas) some process models could not be deployed (see details above)


$ atlas lsp
┌─────────┬─────────────┬────────────────────┐
│ (index) │     id      │   startEventIds    │
├─────────┼─────────────┼────────────────────┤
│    0    │ 'wait_demo' │ [ 'StartEvent_1' ] │
│    1    │ 'Process_1' │ [ 'StartEvent_1' ] │
└─────────┴─────────────┴────────────────────┘
```

WDYT?

**Comment by ElRaptorus** [comment]
Schwierig. Eine 100% saubere Lösung gibt es hier vermutlich nicht.
Ich würde vllt. vorschlagen, beim Deploy durch den Proxy die Definition ID durch die ProcessModelID mit `_Definition` Suffix zu ersetzen (gerne auch ein anderes, falls da jemand eine bessere Idee hat).

Also z.B. wenn das XML einen Prozess `SomeFancyProcess` hat, dann würde die DefinitionId `SomeFancyProcess_Definition` lauten (damit soll sichergestellt sein, dass alle IDs in dem XML unique bleiben).
 
Das würde zwar das XML modifizieren, aber da die ID in der PE ohnehin nie genutzt wurde und im Studio auch (meines Wissens nach, korrigiert mich, wenn ich mich irre @alexanderkasten @SteffenKn ) nur eine ungenutzte, technische ID ist, dürfte das keine Schwierigkeiten verursachen. 

Der Vorteil hier wäre, dass dann der "Name" der deployten ProcessDefinition lesbar bleibt.

**Comment by ElRaptorus** [comment]
Btw, hat das eigentlich einen tieferen Sinn, dass die Issue Überschrift auf englisch und der Issue Text auf deutsch verfasst sind? 😜

**Comment by rrrene** [comment]
> Ich würde vllt. vorschlagen, beim Deploy durch den Proxy die Definition ID durch die ProcessModelID mit `_Definition` Suffix zu ersetzen

Find ich gut 👍

> Btw, hat das eigentlich einen tieferen Sinn, dass die Issue Überschrift auf englisch und der Issue Text auf deutsch verfasst sind?

👀

**Comment by alexanderkasten** [comment]
> Ich würde vllt. vorschlagen, beim Deploy durch den Proxy die Definition ID durch die ProcessModelID mit `_Definition` Suffix zu ersetzen (gerne auch ein anderes, falls da jemand eine bessere Idee hat).

Würdest du das immer machen, oder nur wenn die Definition ID `Definition_1` ist?

**Comment by ElRaptorus** [comment]
> > Ich würde vllt. vorschlagen, beim Deploy durch den Proxy die Definition ID durch die ProcessModelID mit `_Definition` Suffix zu ersetzen (gerne auch ein anderes, falls da jemand eine bessere Idee hat).
> 
> Würdest du das immer machen, oder nur wenn die Definition ID `Definition_1` ist?

Immer.
