### ISSUE TITLE
Can't  list process instances  with Atlas CLI

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/ProcessEngine.CompatibilityProxyAdapter#6]
Es scheint, dass eine Prozess-Modell-ID irrtümlich als Prozess-Instanz-ID verwendet wird.

```
$ atlas lsp
┌─────────┬─────────────┬────────────────────┐
│ (index) │     id      │   startEventIds    │
├─────────┼─────────────┼────────────────────┤
│    0    │ 'wait_demo' │ [ 'StartEvent_1' ] │
│    1    │ 'Process_1' │ [ 'StartEvent_1' ] │
└─────────┴─────────────┴────────────────────┘


$ atlas start wait_demo StartEvent_1
┌─────────┬─────────┬────────────────┬────────────────┬────────────────────────────────────────┬────────────────────────────────────────┬───────┐
│ (index) │ success │ processModelId │  startEventId  │           processInstanceId            │             correlationId              │ error │
├─────────┼─────────┼────────────────┼────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼───────┤
│    0    │  true   │  'wait_demo'   │ 'StartEvent_1' │ '768288e0-a19c-4f98-a69a-c136858c956d' │ '7d7d8ba0-fd44-4507-9b9b-fdf00531c3f4' │       │
└─────────┴─────────┴────────────────┴────────────────┴────────────────────────────────────────┴────────────────────────────────────────┴───────┘


$ atlas lsi
(node:53276) UnhandledPromiseRejectionWarning: NotFoundError: ProcessInstance with ID Process_1 not found.
    at HttpClient.throwEssentialProjectsError (/Users/rrrene/projects/atlas-engine/cli/node_modules/@essential-projects/http/dist/commonjs/http_client.js:110:40)
    at HttpClient.throwErrorFromObject (/Users/rrrene/projects/atlas-engine/cli/node_modules/@essential-projects/http/dist/commonjs/http_client.js:105:18)
    at HttpClient.createAndThrowError (/Users/rrrene/projects/atlas-engine/cli/node_modules/@essential-projects/http/dist/commonjs/http_client.js:86:14)
    at HttpClient.evaluateResponse (/Users/rrrene/projects/atlas-engine/cli/node_modules/@essential-projects/http/dist/commonjs/http_client.js:68:18)
    at HttpClient.get (/Users/rrrene/projects/atlas-engine/cli/node_modules/@essential-projects/http/dist/commonjs/http_client.js:13:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:53276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Gute Nachricht: Die Instanz wurde aber erstellt und ist durchgelaufen: 

```shell
$ atlas show 768288e0-a19c-4f98-a69a-c136858c956d

Model:      wait_demo (Definition: Definition_1)
Instance:   768288e0-a19c-4f98-a69a-c136858c956d (Correlation: 7d7d8ba0-fd44-4507-9b9b-fdf00531c3f4, no parent)
Created:    2020-03-10 03:02:30 (a minute ago)
Finished:   2020-03-10 03:02:30 (took a few seconds)
User:       dummy_token
State:      finished

--- HISTORY -----------------------------------------------------------------------

Token history

    "End" (EndEvent_00hkafj)
    -> "Wait for X seconds" (Task_1izpajn)
    -> "StartEvent CallActivitySubprocess" (StartEvent_1)

Input "End" (EndEvent_00hkafj)

    {
      "iterations": 0
    }

Output "StartEvent CallActivitySubprocess" (StartEvent_1)

    {}
```

Ich hätte gedacht, dass der Call diese Zeile in der CLI betrifft:

https://github.com/atlas-engine/cli/blob/b40e270ff0dbf2e92d6bcb29035dc48ce65508f0/src/commands/list-process-instances/list-process-instances.ts#L188

Aber da macht die oben zitierte Fehlermeldung ja keinen Sinn.

**Comment by ElRaptorus** [comment]
Die Fehlermeldung ist leider etwas irreführend geraten. 

Was hier im Proxy passiert ist folgendes: 

```ts 
    const query: AdminDomainProcessInstanceQuery = {
      processId: processModelId,
    };

    const results = await this.processInstanceService.query(identity, query);

    if (results.processInstances.length === 0) {
      throw new NotFoundError(`ProcessInstance with ID ${processModelId} not found.`);
    }
```

Hier wird ein Query abgesetzt, der alle Prozessinstanzen zu einem bestimmten Prozessmodell zurück liefert. 
Wenn dieser jetzt leer zurück kommt - das kann z.B. passieren, wenn der Benutzer auf keine der aktiven Prozessinstanzen zugreifen darf, oder eben, wenn keine Prozessinstanzen zu diesem Prozessmodell existieren - dann wird der 404 geworfen (mit einer zugegebenermaßen recht irreführenden Message, die sollte man mal nachbessern 👍 ). 

Die AtlasEngine ist da toleranter, die würde einfach ein leeres Array zurück geben, die ProcessEngine war da aber restriktiver, deshalb mussten wir das hier nachbilden.

**Comment by ElRaptorus** [comment]
Dass der Request fehlschlägt, könnte übrigens auf ein Zeitverhalten zurückzuführen sein. 

Ich kenn das Verhalten der CLI jetzt nicht so gut, aber ich vermute mal es passiert hier unmittelbar hintereinander folgendes (korrigiere mich, wenn ich mich irre):

- Command "Start ProcessInstance and return on started"
- Command "Query ProcessInstances for ProcessModel"

Was hier jetzt passieren könnte ist, dass der "Query" Request abgesetzt wird, bevor der State der Prozessinstanz erstmalig persistiert wurde. 

Also dass effektiv folgendes passiert:

- Command "Start ProcessInstance and return on started"
    - Backend: Prozessinstanz wird gestartet
    - Backend: Request resolved
- Command "Query ProcessInstances for ProcessModel"
    - Backend: Prozessinstanz persistiert ihren initialen state

D.h. die Prozessinstanz existiert zu dem Zeitpunkt, an dem der Query losgeschickt wird noch nicht.
Wäre jetzt meine Vermutung. 

Das Verhalten kommt daher zustande, dass das im Falle von "Start ProcessInstance and return on started" das Promise zur Ausführung der Prozessinstanz nicht awaited wird (sonst würde das auch garnicht funktionieren).
Daher kann es eine minimale Zeitdifferenz geben zwischen dem Resolven des Requests und dem Persistieren der Prozessinstanz. 
Wenn der Query jetzt in genau dieser Zeit abgesetzt wird, kommt der leer zurück.

Was du als Workaround versuchen könntest wäre folgendes:
- Auf die `onProcessWithProcessModelIdStarted` Notification subscriben - am besten mit "SubscribeOnce = true"
- Die Prozessinstanz starten
- Wenn die Notification ankommt, den `getProcessInstancesForProcessModel` ausführen

Das sollte das Problem umgehen.

**Comment by rrrene** [comment]
Danke für die Analyse. Ich teste das mal 👍

**Comment by rrrene** [comment]
Der Fehler tritt auf, weil er keine Prozessinstanzen zu einer Prozess-Modell-ID findet (wie du vermutet hast). 👍 Wird jetzt in der CLI abgefangen und behandelt.

Sollten wir denn die Fehlermeldung anpassen? Zumindest ich fand die irreführend, da ich dachte er sucht nach einer Prozessinstanz mit der ID "Process_1": https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/blob/1a37f2fb166d8b864dc5f2dfa5bd345a3aeb61ab/src/management_api/proxy_services/correlation_proxy_service.ts#L173

**Comment by ElRaptorus** [comment]
> Der Fehler tritt auf, weil er keine Prozessinstanzen zu einer Prozess-Modell-ID findet (wie du vermutet hast). 👍 Wird jetzt in der CLI abgefangen und behandelt.

Ok, gut zu wissen. 👍 

> Sollten wir denn die Fehlermeldung anpassen? Zumindest ich fand die irreführend, da ich dachte er sucht nach einer Prozessinstanz mit der ID "Process_1":

Ja sollten wir auf jeden Fall. Ich würde `No ProcessIntances for ProcessModel <InsertProcessModelIdHere> found` vorschlagen.

**Comment by rrrene** [comment]
> Ja sollten wir auf jeden Fall. Ich würde `No ProcessIntances for ProcessModel <InsertProcessModelIdHere> found` vorschlagen.

👍

**Comment by ElRaptorus** [comment]
Done: 
https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/commit/1f1b0225bf1b7c7eeebbedfd75004df3764cf00a

**Comment by rrrene** [comment]
@ElRaptorus Mist. Ich hatte oben einen Rechtschreibfehler drin, der mit im Code gelandet ist: `ProcessIntances` (da fehlt es `s`)

**Comment by ElRaptorus** [comment]
Ups...

**Comment by ElRaptorus** [comment]
Fixed in: https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/pull/9/commits/c43bd8c678b227d9f202aa792f8575af78637992
